### ISSUE TITLE
Groups do not work

### ISSUE THREAD

**Issue by IonRoux** [ladikvadim/Telegram-Bot#1]
Hi, Playing around with this and I found that groups do not work.  The ID number for groups is larger than the signed 32 bit number being used for it in the type def. Changing this to a 64bit one works and allows the bot to see group messag
![typedef](https://user-images.githubusercontent.com/1173900/40580468-7e9632e8-60f3-11e8-9fbe-aed86efa554e.PNG)
es.

**Comment by ladikvadim** [comment]
olithraz, thanks for remark

**Comment by ladikvadim** [comment]
Fixed
